OSX uses MAP_ANON instead of MAP_ANONYMOUS
Was running into this issue when compiling on OSX:

```
error: use of undeclared identifier 'MAP_ANONYMOUS'
```

Did a Google search and came across:

https://j.ee.washington.edu/trac/gmtk/ticket/371

Applied that patch to the .c file and things seem to work