Change `publish` test to `package` test
When run with the nightly toolchain, the `publish` test recently started failing with the following:
```
error: crate afl@0.15.10 already exists on crates.io index
```
I think this is the cause: https://github.com/rust-lang/cargo/blob/6ede1e2b276eaf93618765a08bd3ec2f0f44d955/src/cargo/ops/registry/publish.rs#L136

See, for example: https://github.com/rust-lang/cargo/pull/14550/files#r1763454347